### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/mergin-db-sync#14]
After running some time the daemon has crashed with this error:
```
Trying to push
Traceback (most recent call last):
  File "dbsync_daemon.py", line 31, in <module>
    dbsync.dbsync_push()
  File "/home/ubuntu/mergin-db-sync/dbsync.py", line 329, in dbsync_push
    _geodiff_create_changeset(config.db_driver, config.db_conn_info, config.db_schema_base, config.db_schema_modified, tmp_changeset_file)
  File "/home/ubuntu/mergin-db-sync/dbsync.py", line 112, in _geodiff_create_changeset
    _run_geodiff([config.geodiffinfo_exe, "createChangesetEx", driver, conn_info, base, modified, changeset])
  File "/home/ubuntu/mergin-db-sync/dbsync.py", line 103, in _run_geodiff
    res = subprocess.run(cmd, stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1254, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

**Comment by wonder-sk** [comment]
Should be fixed in geodiff 0.8.5, mergin python client 0.5.1
